### ISSUE TITLE
Cannot list network interfaces in docker container

### ISSUE THREAD

**Issue by DamienDub** [DEWETRON/TRION-SDK#12]
Hello,

We are trying to Dockerize a C program based on the Trion SDK.

Unfortunately, the C program throws this error when the ListNetworkInterfaces() function is called: `ERR_TARGET_UNKNOWN (100008)`
The same program works fine on the host machine.

The docker image is based on Ubuntu 22, the Dewetron packages are installed and the Trion SDK compiled properly.
The docker image is ran with `--privileged` and `--network host` options to allow access of the host network interfaces.
We ran a small C program in order to list the network interfaces in the host machine and in the docker container, it works fine in both cases.

Do you have some information regarding this error in order to further troubleshoot the issue ?

Thanks and best regards

**Comment by glaure** [comment]
Hello,

i just tried to run  TN_OneAnalogChannel in an unpriviliged docker container.

ListNetworkInterfaces prints following output:

`<?xml version="1.0"?>
  <Network>
    <Enumerate>
      <Interface name="lo" index="1" hwaddress="00:00:00:00:00:00" flags="65609">
        <Address family="1" address="127.0.0.1" mask="255.0.0.0" broadcast=""/>
        <Address family="2" address="::1" mask="ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff" broadcast=""/>
        </Interface>
      <Interface name="eth0" index="127" hwaddress="02:42:ac:11:00:02" flags="69699">
        <Address family="1" address="172.17.0.2" mask="255.255.0.0" broadcast="172.17.255.255"/>
        <Address family="2" address="fd00::242:ac11:2" mask="ffff:ffff:ffff:ffff:ffff::" broadcast="ffff:ffff:ffff:ffff:ffff::"/>
        <Address family="2" address="fe80::42:acff:fe11:2%eth0" mask="ffff:ffff:ffff:ffff::" broadcast="ffff:ffff:ffff:ffff::"/>
        </Interface>
      </Enumerate>
    </Network>
`

I am pretty sure your problem is, that you use TRION API (that is used to access local hardware). If you want to use net devices (TRIONet, NexDAQ), you have to use TRIONET API instead.

You have to use following define:

USE_TRIONET_API

which is shown in the examples CMakeList files:

`  set_property(TARGET ${SAMPLE}
    APPEND
    PROPERTY COMPILE_DEFINITIONS
    USE_TRIONET_API
  )`

I am able to reproduce 
Error: ERR_TARGET_UNKNOWN (100008)
when I deliberatly enable ListNetworkInterface in TRION examples. This is correct behaviour.

I hope this information helps!

Best regards,
Gunther

**Comment by glaure** [comment]
I am sorry that the SDK documentation does not explain this. We will try to improve.

Bye Gunther

**Comment by DamienDub** [comment]
Hello Gunther,

Thanks for the reply. We actually do define the USE_TRIONET_API flag.

Here's a Dockfile to reproduce the issue we have:

```dockerfile
# Use the Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set the working directory inside the container
WORKDIR /opt

# Update the package list and install dependencies for Dewetron package
# This might be simplified at some point
RUN apt update && \
    apt install -y --no-install-recommends \
    git \
    cmake \
    build-essential \
    ca-certificates \ 
    libpci-dev \
    libboost-all-dev \
    dkms \
    qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
    libczmq4 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libmatio11 libmodbus5 \
    libqt5multimedia5 libqt5positioning5 libqt5qml5 libqt5quick5 libqt5svg5 vpx-tools mkvtoolnix \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
    libgstreamer-plugins-good1.0-0 libgstreamer-plugins-bad1.0-0 libvpx7 liborc-0.4-0 \
    libqt5multimedia5-plugins qml-module-qtquick-dialogs qml-module-qtquick-xmllistmodel \
    qml-module-qt-labs-folderlistmodel qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-shapes \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

# Install Dewetron package
# We might save space by intalling packages independently at some point
COPY dewetron-apps-6.7.1.94-jammy.install .
RUN ./dewetron-apps-6.7.1.94-jammy.install

# Clone the TRION-SDK repository from GitHub and checkout tag TRION-R7.0.0
RUN git clone --no-checkout https://github.com/DEWETRON/TRION-SDK.git && \
    cd TRION-SDK && \
    git fetch --tags && \
    git checkout tags/TRION-R7.0.0

# Configure and build TRION-SDK samples. This also builds the trion_sdk_utils static lib
RUN cd TRION-SDK/trion/C && mkdir build && cd build && cmake .. && make
RUN cd TRION-SDK/trionet/C && mkdir build && cd build && cmake .. && make

# Copy tn_one_analog_channel sample and compile it directly
RUN cp TRION-SDK/trionet/C/analog/TN_OneAnalogChannel/tn_one_analog_channel.c .
RUN /usr/bin/cc -DUNIX -DUSE_TRIONET_API -DBUILD_X64 \
    -I/opt/TRION-SDK/trion_sdk_util/C \
    -I/opt/TRION-SDK/trion_api/C/inc \
    -Wmultichar -fPIC -rdynamic -MD -MT -MF -g tn_one_analog_channel.c \
    /opt/TRION-SDK/trion/C/build/trion_sdk_util/libtrion_sdk_util_C.a \
    -ldl \
    -lpthread \
    -o TN_OneAnalogChannel

# Container entry point
CMD ["/bin/bash"]
```

In this docker container, we compile the Trion SDK samples. We also copy the tn_one_analog_channel and compile it directly.
When running the samples within the docker container: 
- the sample provided with the SDK runs fine
- the sample compiled direclty gives a ERR_TARGET_UNKNOWN  error

We did the same thing on the host machine and both samples ran fine.

What did we miss that would cause the sample compiled in the docker container to fail ?

Best regards

**Comment by glaure** [comment]
The issue is the usage of trion_sdk_utils atatic lib:

From trion_sdk_util.c

```
#include <stdio.h>
#include <string.h>
#ifdef USE_TRIONET_API
#  include "dewepxinet_load.h"
#else
#  include "dewepxi_load.h"
#endif
#include "dewepxi_apicore.h"
#include "dewepxi_types.h"
#include "trion_sdk_util.h"
#ifdef WIN32
#include "dewepxi_apiutil.h"
#else
#include <stdio.h>
#endif
```

It also has to be build with USE_TRIONET_API defined.

Bye Gunther

**Comment by DamienDub** [comment]
Well done, we missed the fact that the utility lib was also compiled for trionet.

Thanks Gunther, I'm closing the ticket
