### ISSUE TITLE
TRION SDK example with 1600 Trion and CBL D16 + MSI

### ISSUE THREAD

**Issue by arnaudDewetronfrance** [DEWETRON/TRION-SDK#3]
Dear all , 
Is it possible to have example or functions to use a TRION board 1600 or 1802 dlv with CBL D16 and MSIs with C drivers ? 
Regards

**Comment by glaure** [comment]
Hi Anaud,

InterfacingTEDSEX would be the example to start. The CB16D device is connected using RS485 and uses a serial I2C protocol for communication. 
That allows TRION-API to read connected MSIs using its normal TEDS commands.

I am working on an example explaining it a bit better,

cu Gunther

**Comment by glaure** [comment]
Good morning!

About your question:
_I don’t see ( or understand)  how to change the range of the MSI => 100 V , 200 V , 1000 V into the code._

The ranges are implemented in changing the voltage range of the TRION board:
`nErrorCode = DeWeSetParamStruct_str(sTarget, "Range", "10V");`

The TRION-1802-dLV and TRION-1600-dLV allow a range between 2.5V and 10V. 
For MSI-BR-V-200 the ranges are:
200 V ->  10V
100 V -> 5V
40 V -> 2.5V
20 V -> 2.5V

40V and 20V are in fact the same range only showing the set max and min range value in OXYGEN instruments.
Note; The minimum voltage range is 2.5V. Thats why it is important to **read the adjusted range back** from the board and use that value for scaling!

Best regards,
Gunther
