### ISSUE TITLE
trionet access in remote with SDK

### ISSUE THREAD

**Issue by arnaudDewetronfrance** [DEWETRON/TRION-SDK#4]
Dear , 

ERR_TARGET_UNKNOWN (100008) is raised. IP are correclty defined
 
We have done multiples tests ( usb cables , ethernet cables ) Windows 7 is used 
 
System is well done from dewetron explorer and no demo unit activated at the same time. 
 
Regards

**Comment by mponiz** [comment]
Dear Arnaud,

Which of the examples are you trying to run?

Could you provide the source-line (or the api-command with it's parameters) which results in the errorcode ERR_TARGET_UNKNOWN?

Thank you and Best Regards

**Comment by arnaudDewetronfrance** [comment]
Dear ,

Examples run are from the demo SDK TRIONET_ListBoards and OneAnalogChannels ( just IP address changed )

Regards

**Comment by arnaudDewetronfrance** [comment]
Here joined , the user source code.

Customer told me that he uses windev  ( I don’t know )

Regards


From: Arnaud Genebrier
Sent: mercredi 10 novembre 2021 09:17
To: 'DEWETRON/TRION-SDK' ***@***.***>; DEWETRON/TRION-SDK ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [DEWETRON/TRION-SDK] trionet access in remote with SDK (Issue #4)

Dear ,

Examples run are from the demo SDK TRIONET_ListBoards and OneAnalogChannels ( just IP address changed )

Regards

**Comment by arnaudDewetronfrance** [comment]
Dear all ,

I have compiled on my side the example for TRIONET and it doesn’t work also on my side with SDK source examples provided.

Regards

From: Arnaud Genebrier
Sent: mercredi 10 novembre 2021 16:39
To: 'DEWETRON/TRION-SDK' ***@***.***>; 'DEWETRON/TRION-SDK' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [DEWETRON/TRION-SDK] trionet access in remote with SDK (Issue #4)

Here joined , the user source code.

Customer told me that he uses windev  ( I don’t know )

Regards


From: Arnaud Genebrier
Sent: mercredi 10 novembre 2021 09:17
To: 'DEWETRON/TRION-SDK' ***@***.******@***.***>>; DEWETRON/TRION-SDK ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [DEWETRON/TRION-SDK] trionet access in remote with SDK (Issue #4)

Dear ,

Examples run are from the demo SDK TRIONET_ListBoards and OneAnalogChannels ( just IP address changed )

Regards

**Comment by moberhofer** [comment]
Dear Arnaud,

we will check this on our side with a clean GitHub checkout. Maybe there is an issue with the source.

Best Regards,
Michael

**Comment by mponiz** [comment]
Dear Arnaud,

Did you setup the project via cmake as described in README.md, or did you set it up manually.

Background for the question:
Using cmake the project will be set up with the define "USE_TRIONET_API" set.
This define ensures that the trionet-wrapper-api is loaded, that expands the api with the net-capability.

The error-code ERR_TARGET_UNKNOWN (100008) most probably is raised during the 2 commands setting up the network-interface, which would be a hint that the non-net-capable api has been loaded.

Regards
Martin

**Comment by arnaudDewetronfrance** [comment]
Hi Martin ,

On my side , i use cmake.

Until now , I used examples from trions application msi by selection Trion SDK during installation.

I have retried with SDK from github always with cmake.

No way to communicate with TRIONET => error : No Trion board found.

Firmware on Trionet is 5.4 version and DEWE2 Driver is 5.7 on my side.

Regards

**Comment by mponiz** [comment]
Hello Arnaud,

That reads like a seperate issue, than the one of the original post (ERR_TARGET_UNKNOWN)

I would like to attach some screenshots, but my windows installation is in german language - so it would be of little use. So I will go with a verbal description.
Don't hessitate to come back, if you need assistance or clarification.

Two things come to my mind, that may cause that behaviour.
Please start with checking possiblity (a).

### a.) passing the wrong IP-address to the api in `configureNetwork()`

**The Address that needs to be passed should be the address of your local adapter, and not the address of the TRIONet you try to communicate with.**

In `configureNetwork()` you shoud see the lines
`    // Optional: Prints available network interfaces`
`    //ListNetworkInterfaces();`

Please uncomment ListNetworkInterfaces, recompile and the exmple run again.

This will dump a list of available network-adapters from your system.
Find the one, that looks like having a simialar IP-address than the TRIONet you are trying to communicat with (the first 2 octets should be the same, if the subnet-mask is "255.255.0.0", the flags need to be "4103", indicating the active ones.)
Pass this IP as `address` in `configureNetwork()`

Please try again, with this address.

If the issue persists please consider the firewall settings.

### b.) Windows Firewall disallowing traffic from the self-built-aplication.

I have had this happening to me yesterday also, and it took me a moment to realize, why the example didn't work.

Could you please try the following steps:

-  open the windows firewall (pressing ctrl-esc, and typing "firewall" should take you there)
- click "Choose Allow an App through Windows Firewall."
- you now should see an elaborate list of various applications and services with 1 checkbox in front, and 3 columns with checkboxes after the name
- scroll all the way down, till you find "trionet_listboards"
- make sure all checkboxes are checked and confirm with OK

Alternatively you could also delete the current rule for "trionet_listboards". In that case the next time you start the application windows will give you a firewall-confirmation-dialog.

Here it is important to check all 3 checkboxes. The USB network is considered a public network from point of view of the firewall as far as I am aware.

Now start the trionet_listboards example again, and see, if the issue persists.

Regards
Martin

**Comment by arnaudDewetronfrance** [comment]
Dear ,

Thank for the help.

It works

Regards
