### ISSUE TITLE
Python Package Support

### ISSUE THREAD

**Issue by willjschmitt** [DEWETRON/TRION-SDK#9]
I'd like to include the TRION Python SDK into our tools that leverage Dewetron TRION equipment, and while I might understand you aren't publishing to PyPi, the Python SDK folder doesn't contain any package definitions which doesn't afford the ability to pip install at all using a git URL (e.g. how the [`pyDmdReader` package](https://github.com/DEWETRON/pyDmdReader) suggests installation). The example assumes a checkout of this repository, adding the Python bindings as a [manual path modification](https://github.com/DEWETRON/TRION-SDK/blob/master/trionet/python/TN_TrionMeasure/tn_trion_measure_qt.py#L6), suggesting its the expected approach, which is pretty unideal for anything except a quick script. I'd like to be able to use the standard Python tools at the very least, so is there a world where a `setup.py` (or `pyproject.toml`) could be defined for the Python package, so that we can install with `pip`?

Secondarily, it would be nice not to have to use a GUI installer for the Dewetron API to be able to use the SDK, instead hermetically including it as a dependency of our build process (perhaps as a dll/so with a published package to PyPi), but I get that might be a harder reach (although very much desired)

**Comment by matthiasstraka** [comment]
Thanks for the request. It is certainly possible to package the python binding into something that PIP can install directly from GitHub. We are currently busy with other projects, but I will take a look at it in the near future and comment progress on this ticket.

**Comment by matthiasstraka** [comment]
We updated or python support and merged the changes into the main branch. You can now install python support via PIP using
```cmd
pip install git+https://github.com/DEWETRON/TRION-SDK.git
```
and use the TRION SDK in Python as follows:
```python
from trion_sdk import *

DeWePxiLoad()

error_code, num_boards = DeWeDriverInit()

if num_boards != 0:
    error_code = DeWeSetParam_i32( 0, CMD_OPEN_BOARD_ALL )
    error_code = DeWeSetParam_i32( 0, CMD_RESET_BOARD_ALL )

    # Your program goes here

    error_code = DeWeSetParam_i32( 0, CMD_CLOSE_BOARD_ALL )

DeWePxiUnload()
```
